#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
    echo "This script required the architecture to build as a command line argument."
	echo "See:"
	echo "https://docs.microsoft.com/de-de/dotnet/core/rid-catalog"
	echo "for valid values."
	exit 1
fi

dotnet publish -r $1 -p:PublishSingleFile=true -c Release --self-contained true

mkdir -p out
LOCATION="bin/Release/net5.0/${1}/publish"
cd ${LOCATION}
rm *.dll
rm *.pdb
zip -r "${1}" *
cd -
mv "${LOCATION}/${1}.zip" out/

